# Customer Churn Prediction — Model Training

This notebook trains and compares Logistic Regression and Random Forest models.
The target is `Churn`, where Yes = 1 and No = 0.

In [1]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df = df.dropna(subset=['TotalCharges']).drop_duplicates().reset_index(drop=True)
df = df.drop(columns=['customerID'])
X = df.drop(columns=['Churn'])
y = df['Churn'].map({'No': 0, 'Yes': 1})
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
print('Training rows:', len(X_train))
print('Test rows:', len(X_test))

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [ ]:
numeric = X.select_dtypes(include=['number']).columns.tolist()
categorical = X.select_dtypes(exclude=['number']).columns.tolist()
preprocessor = ColumnTransformer([
    ('numeric', Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())]), numeric),
    ('categorical', Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))]), categorical)
])

In [ ]:
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=300, max_depth=12, min_samples_leaf=2, class_weight='balanced', random_state=42, n_jobs=-1)
}

results = {}
for name, estimator in models.items():
    pipeline = Pipeline([('preprocessor', preprocessor), ('model', estimator)])
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)
    probabilities = pipeline.predict_proba(X_test)[:, 1]
    results[name] = {'model': pipeline, 'roc_auc': roc_auc_score(y_test, probabilities)}
    print(f'\n{name}')
    print(classification_report(y_test, predictions, target_names=['No Churn', 'Churn']))
    print('Confusion matrix:')
    print(confusion_matrix(y_test, predictions))
    print(f'ROC-AUC: {results[name]["roc_auc"]:.4f}')

In [4]:
df = pd.read_csv(
    'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
)

FileNotFoundError: [Errno 2] No such file or directory: 'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [5]:
df = pd.read_csv(
    'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
)

FileNotFoundError: [Errno 2] No such file or directory: 'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [6]:
!python customer-churn-prediction/src/download_data.py

python3: can't open file '/content/customer-churn-prediction/src/download_data.py': [Errno 2] No such file or directory

In [7]:
!ls customer-churn-prediction/data/raw/

ls: cannot access 'customer-churn-prediction/data/raw/': No such file or directory

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv(
    'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
)

df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

df = (
    df.dropna(subset=['TotalCharges'])
      .drop_duplicates()
      .reset_index(drop=True)
)

df = df.drop(columns=['customerID'])

X = df.drop(columns=['Churn'])
y = df['Churn'].map({'No': 0, 'Yes': 1})

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print('Training rows:', len(X_train))
print('Test rows:', len(X_test))

FileNotFoundError: [Errno 2] No such file or directory: 'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [9]:
!git clone https://github.com/Hadi-Saeed-2006/customer-churn-prediction.git

Cloning into 'customer-churn-prediction'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 67 (delta 23), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (67/67), 17.73 KiB | 1.36 MiB/s, done.
Resolving deltas: 100% (23/23), done.

In [10]:
!ls customer-churn-prediction

data	 models     README.md		  requirements.txt  visualizations
LICENSE  notebooks  requirements-dev.txt  src

In [11]:
!python customer-churn-prediction/src/download_data.py

Downloading IBM Telco Customer Churn dataset...
Traceback (most recent call last):
  File "/usr/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.12/http/client.py", line 1358, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1404, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1353, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1113, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1057, in send
    self.connect()
  File "/usr/lib/python3.12/http/client.py", line 1499, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1010)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/customer-churn-prediction/src/download_data.py", line 27, in <module>
    download_dataset()
  File "/content/customer-churn-prediction/src/download_data.py", line 21, in download_dataset
    urlretrieve(DATA_URL, OUTPUT_PATH)
  File "/usr/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1010)>

In [12]:
!ls -lh customer-churn-prediction/data/raw/

total 4.0K
-rw-r--r-- 1 root root 604 Aug  9 09:04 README.md

In [13]:
!wget -O customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv \
"https://raw.githubusercontent.com/IBM/customer-churn-prediction/master/data/WA_Fn-UseC_-Telco-Customer-Churn.csv"

--2026-08-09 09:08:28--  https://raw.githubusercontent.com/IBM/customer-churn-prediction/master/data/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2026-08-09 09:08:28 ERROR 404: Not Found.

In [14]:
!ls -lh customer-churn-prediction/data/raw/

total 4.0K
-rw-r--r-- 1 root root 604 Aug  9 09:04 README.md
-rw-r--r-- 1 root root   0 Aug  9 09:08 WA_Fn-UseC_-Telco-Customer-Churn.csv

In [15]:
!wget -O customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv \
"https://community.watsonanalytics.com/wp-content/uploads/2015/03/WA_Fn-UseC_-Telco-Customer-Churn.csv"

--2026-08-09 09:10:01--  https://community.watsonanalytics.com/wp-content/uploads/2015/03/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving community.watsonanalytics.com (community.watsonanalytics.com)... 199.46.34.76
Connecting to community.watsonanalytics.com (community.watsonanalytics.com)|199.46.34.76|:443... connected.
OpenSSL: error:0A000458:SSL routines::tlsv1 unrecognized name
Unable to establish SSL connection.

In [16]:
!ls -lh customer-churn-prediction/data/raw/

total 4.0K
-rw-r--r-- 1 root root 604 Aug  9 09:04 README.md
-rw-r--r-- 1 root root   0 Aug  9 09:10 WA_Fn-UseC_-Telco-Customer-Churn.csv

In [17]:
import pandas as pd

df = pd.read_csv(
    'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
)

print("Dataset shape:", df.shape)
display(df.head())

EmptyDataError: No columns to parse from file

In [18]:
!rm -f customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv

In [19]:
!wget -O customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv \
"https://raw.githubusercontent.com/treselle-systems/customer_churn_analysis/master/WA_Fn-UseC_-Telco-Customer-Churn.csv"

--2026-08-09 09:11:22--  https://raw.githubusercontent.com/treselle-systems/customer_churn_analysis/master/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 970457 (948K) [text/plain]
Saving to: ‘customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv’

customer-churn-pred 100%[===================>] 947.71K  --.-KB/s    in 0.05s

2026-08-09 09:11:22 (19.0 MB/s) - ‘customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv’ saved [970457/970457]

In [20]:
!ls -lh customer-churn-prediction/data/raw/

total 952K
-rw-r--r-- 1 root root  604 Aug  9 09:04 README.md
-rw-r--r-- 1 root root 948K Aug  9 09:11 WA_Fn-UseC_-Telco-Customer-Churn.csv

In [21]:
import pandas as pd

df = pd.read_csv(
    'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
)

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv(
    'customer-churn-prediction/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
)

df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

df = (
    df.dropna(subset=['TotalCharges'])
      .drop_duplicates()
      .reset_index(drop=True)
)

df = df.drop(columns=['customerID'])

X = df.drop(columns=['Churn'])
y = df['Churn'].map({'No': 0, 'Yes': 1})

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Training rows:", len(X_train))
print("Test rows:", len(X_test))

Training rows: 5625
Test rows: 1407

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric = X.select_dtypes(include=['number']).columns.tolist()
categorical = X.select_dtypes(exclude=['number']).columns.tolist()

preprocessor = ColumnTransformer([
    (
        'numeric',
        Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler())
        ]),
        numeric
    ),
    (
        'categorical',
        Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(
                handle_unknown='ignore',
                sparse_output=False
            ))
        ]),
        categorical
    )
])

In [24]:
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(
        max_iter=1000,
        class_weight='balanced',
        random_state=42
    ))
])

logistic_model.fit(X_train, y_train)

logistic_predictions = logistic_model.predict(X_test)
logistic_probabilities = logistic_model.predict_proba(X_test)[:, 1]

print("Logistic Regression trained successfully!")

Logistic Regression trained successfully!

In [25]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print(classification_report(
    y_test,
    logistic_predictions,
    target_names=['No Churn', 'Churn']
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, logistic_predictions))

print(
    "ROC-AUC:",
    round(roc_auc_score(y_test, logistic_probabilities), 4)
)

              precision    recall  f1-score   support

    No Churn       0.90      0.70      0.79      1033
       Churn       0.49      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

Confusion Matrix:
[[723 310]
 [ 76 298]]
ROC-AUC: 0.8351

In [26]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=2,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1
    ))
])

random_forest_model.fit(X_train, y_train)

rf_predictions = random_forest_model.predict(X_test)
rf_probabilities = random_forest_model.predict_proba(X_test)[:, 1]

print("Random Forest trained successfully!")

Random Forest trained successfully!

In [27]:
print(classification_report(
    y_test,
    rf_predictions,
    target_names=['No Churn', 'Churn']
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))

print(
    "ROC-AUC:",
    round(roc_auc_score(y_test, rf_probabilities), 4)
)

              precision    recall  f1-score   support

    No Churn       0.87      0.80      0.83      1033
       Churn       0.55      0.68      0.61       374

    accuracy                           0.77      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.79      0.77      0.77      1407

Confusion Matrix:
[[827 206]
 [121 253]]
ROC-AUC: 0.8282

In [28]:
import pandas as pd
import numpy as np

# Get the fitted preprocessing pipeline
fitted_preprocessor = logistic_model.named_steps['preprocessor']
fitted_model = logistic_model.named_steps['model']

# Get transformed feature names
feature_names = fitted_preprocessor.get_feature_names_out()

# Get Logistic Regression coefficients
coefficients = fitted_model.coef_[0]

# Create feature importance table
feature_importance = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients,
    'Absolute_Importance': np.abs(coefficients)
})

# Sort by importance
feature_importance = feature_importance.sort_values(
    'Absolute_Importance',
    ascending=False
)

feature_importance.head(20)

,Feature,Coefficient,Absolute_Importance
1,numeric__tenure,-1.250374,1.250374
38,categorical__Contract_Two year,-0.777701,0.777701
36,categorical__Contract_Month-to-month,0.696066,0.696066
16,categorical__InternetService_Fiber optic,0.660906,0.660906
2,numeric__MonthlyCharges,-0.621137,0.621137
3,numeric__TotalCharges,0.607433,0.607433
15,categorical__InternetService_DSL,-0.588834,0.588834
28,categorical__TechSupport_No internet service,-0.256902,0.256902
25,categorical__DeviceProtection_No internet service,-0.256902,0.256902
17,categorical__InternetService_No,-0.256902,0.256902
19,categorical__OnlineSecurity_No internet service,-0.256902,0.256902
34,categorical__StreamingMovies_No internet service,-0.256902,0.256902
31,categorical__StreamingTV_No internet service,-0.256902,0.256902
22,categorical__OnlineBackup_No internet service,-0.256902,0.256902
32,categorical__StreamingTV_Yes,0.252081,0.252081
35,categorical__StreamingMovies_Yes,0.244732,0.244732
12,categorical__MultipleLines_No,-0.236824,0.236824
43,categorical__PaymentMethod_Electronic check,0.229096,0.229096
39,categorical__PaperlessBilling_No,-0.219091,0.219091
9,categorical__Dependents_Yes,-0.205760,0.205760

In [29]:
feature_importance.head(15)

,Feature,Coefficient,Absolute_Importance
1,numeric__tenure,-1.250374,1.250374
38,categorical__Contract_Two year,-0.777701,0.777701
36,categorical__Contract_Month-to-month,0.696066,0.696066
16,categorical__InternetService_Fiber optic,0.660906,0.660906
2,numeric__MonthlyCharges,-0.621137,0.621137
3,numeric__TotalCharges,0.607433,0.607433
15,categorical__InternetService_DSL,-0.588834,0.588834
28,categorical__TechSupport_No internet service,-0.256902,0.256902
25,categorical__DeviceProtection_No internet service,-0.256902,0.256902
17,categorical__InternetService_No,-0.256902,0.256902
19,categorical__OnlineSecurity_No internet service,-0.256902,0.256902
34,categorical__StreamingMovies_No internet service,-0.256902,0.256902
31,categorical__StreamingTV_No internet service,-0.256902,0.256902
22,categorical__OnlineBackup_No internet service,-0.256902,0.256902
32,categorical__StreamingTV_Yes,0.252081,0.252081

In [30]:
print("Top factors associated with CHURN:")
display(
    feature_importance
    .sort_values('Coefficient', ascending=False)
    .head(10)
)

print("Top factors associated with RETENTION:")
display(
    feature_importance
    .sort_values('Coefficient', ascending=True)
    .head(10)
)

Top factors associated with CHURN:

,Feature,Coefficient,Absolute_Importance
36,categorical__Contract_Month-to-month,0.696066,0.696066
16,categorical__InternetService_Fiber optic,0.660906,0.660906
3,numeric__TotalCharges,0.607433,0.607433
32,categorical__StreamingTV_Yes,0.252081,0.252081
35,categorical__StreamingMovies_Yes,0.244732,0.244732
43,categorical__PaymentMethod_Electronic check,0.229096,0.229096
18,categorical__OnlineSecurity_No,0.199371,0.199371
27,categorical__TechSupport_No,0.176853,0.176853
14,categorical__MultipleLines_Yes,0.122750,0.122750
26,categorical__DeviceProtection_Yes,0.083315,0.083315

Top factors associated with RETENTION:

,Feature,Coefficient,Absolute_Importance
1,numeric__tenure,-1.250374,1.250374
38,categorical__Contract_Two year,-0.777701,0.777701
2,numeric__MonthlyCharges,-0.621137,0.621137
15,categorical__InternetService_DSL,-0.588834,0.588834
28,categorical__TechSupport_No internet service,-0.256902,0.256902
19,categorical__OnlineSecurity_No internet service,-0.256902,0.256902
17,categorical__InternetService_No,-0.256902,0.256902
25,categorical__DeviceProtection_No internet service,-0.256902,0.256902
31,categorical__StreamingTV_No internet service,-0.256902,0.256902
22,categorical__OnlineBackup_No internet service,-0.256902,0.256902

In [31]:
print("Factors associated with HIGHER churn:")
display(
    feature_importance
    .sort_values('Coefficient', ascending=False)
    .head(15)
)

Factors associated with HIGHER churn:

,Feature,Coefficient,Absolute_Importance
36,categorical__Contract_Month-to-month,0.696066,0.696066
16,categorical__InternetService_Fiber optic,0.660906,0.660906
3,numeric__TotalCharges,0.607433,0.607433
32,categorical__StreamingTV_Yes,0.252081,0.252081
35,categorical__StreamingMovies_Yes,0.244732,0.244732
43,categorical__PaymentMethod_Electronic check,0.229096,0.229096
18,categorical__OnlineSecurity_No,0.199371,0.199371
27,categorical__TechSupport_No,0.176853,0.176853
14,categorical__MultipleLines_Yes,0.122750,0.122750
26,categorical__DeviceProtection_Yes,0.083315,0.083315
21,categorical__OnlineBackup_No,0.079856,0.079856
0,numeric__SeniorCitizen,0.075727,0.075727
40,categorical__PaperlessBilling_Yes,0.034261,0.034261
8,categorical__Dependents_No,0.020931,0.020931
23,categorical__OnlineBackup_Yes,-0.007785,0.007785

In [32]:
print("Factors associated with LOWER churn:")
display(
    feature_importance
    .sort_values('Coefficient', ascending=True)
    .head(15)
)

Factors associated with LOWER churn:

,Feature,Coefficient,Absolute_Importance
1,numeric__tenure,-1.250374,1.250374
38,categorical__Contract_Two year,-0.777701,0.777701
2,numeric__MonthlyCharges,-0.621137,0.621137
15,categorical__InternetService_DSL,-0.588834,0.588834
28,categorical__TechSupport_No internet service,-0.256902,0.256902
19,categorical__OnlineSecurity_No internet service,-0.256902,0.256902
17,categorical__InternetService_No,-0.256902,0.256902
25,categorical__DeviceProtection_No internet service,-0.256902,0.256902
31,categorical__StreamingTV_No internet service,-0.256902,0.256902
22,categorical__OnlineBackup_No internet service,-0.256902,0.256902
34,categorical__StreamingMovies_No internet service,-0.256902,0.256902
12,categorical__MultipleLines_No,-0.236824,0.236824
39,categorical__PaperlessBilling_No,-0.219091,0.219091
9,categorical__Dependents_Yes,-0.205760,0.205760
41,categorical__PaymentMethod_Bank transfer (auto...,-0.181211,0.181211

In [33]:
display(
    feature_importance
    .sort_values('Coefficient', ascending=False)
    .head(15)
)

,Feature,Coefficient,Absolute_Importance
36,categorical__Contract_Month-to-month,0.696066,0.696066
16,categorical__InternetService_Fiber optic,0.660906,0.660906
3,numeric__TotalCharges,0.607433,0.607433
32,categorical__StreamingTV_Yes,0.252081,0.252081
35,categorical__StreamingMovies_Yes,0.244732,0.244732
43,categorical__PaymentMethod_Electronic check,0.229096,0.229096
18,categorical__OnlineSecurity_No,0.199371,0.199371
27,categorical__TechSupport_No,0.176853,0.176853
14,categorical__MultipleLines_Yes,0.122750,0.122750
26,categorical__DeviceProtection_Yes,0.083315,0.083315
21,categorical__OnlineBackup_No,0.079856,0.079856
0,numeric__SeniorCitizen,0.075727,0.075727
40,categorical__PaperlessBilling_Yes,0.034261,0.034261
8,categorical__Dependents_No,0.020931,0.020931
23,categorical__OnlineBackup_Yes,-0.007785,0.007785

## Interpretation

After running the notebook, compare the models using recall, F1-score, and ROC-AUC.
For churn prediction, recall is important because failing to identify a customer who is likely to churn can represent a missed retention opportunity.